# Make all the things necessary for running and looking at output for 
# Reflectivity code on Linux

gfortran crfl2sac.f /opt/sac/lib/sacio.a -o /Users/garnero/bin/crfl2sac 

#g95 16384_crfl.f -O2 -ftrace=frame -o /Users/garnero/bin/crfl
gfortran 16384_crfl.f -o /Users/garnero/bin/crfl

